### PR TITLE
Added disk form_factor meta label

### PR DESCRIPTION
**Pull request by k0ste**
The requirement from field engineers is knowledge of the form factor of the device, i.e. `3.5"`, `2.5"`. Not always possible to determine where is device is installed. When device is 2.5 in 36-disk 4U chassis is definitely in rear cage, for example

Screen Shot 2022-10-14 at 13 43 41

* updated EXAMPLE.md
* fixed copy-paste issue `Starting` **systemd**`_exporter`

### CODE REVIEW

**Comment by k0ste** [comment]
@SuperQ

**Comment by k0ste** [comment]
Moved release changes to #87

**Comment by lahwaacz** [comment]
`smartctl --json` reports `"rotation_rate": 7200` and `"rotation_rate": 0` for my two disks, so the data is in the source.

**Comment by k0ste** [comment]
> Another related feature that I don't see is a way to tell if its an ssd or hdd. Would that be easy to add too?

HDD: `smartctl_device{interface="sat"} * on(device) group_left() (smartctl_device_rotation_rate > 0)`
SATA SSD: `smartctl_device{interface="sat"} * on(device) group_left() (smartctl_device_rotation_rate == 0)`
NVMe: `smartctl_device{interface="nvme"}`

**Comment by k0ste** [comment]
@SuperQ, can you look this? Seems we at finish line with couple of PR's to make a 0.9.0 release 🙏

**Review by SuperQ — APPROVED** [review]
Thanks!

**Pull request merged**
