### PR TITLE
feat: add JSON testing data

### PR DESCRIPTION
**Pull request by robbat2**
- Add README about test data.
- Add script to redact sensitive fields.
- Add JSON testing data collected from many systems, with redaction of sensitive fields.

The initial corpus includes:
- NVME drives
- SAS drives - HDD only, no SSD
- SCSI drives - HDD only, no SSD
- SATA drives - SSD & HDD

### CODE REVIEW

**Comment by robbat2** [comment]
@NiceGuyIT  here's the test data PR as requested; with some redaction tooling.

**Comment by k0ste** [comment]
This will be merged and used for CI? 🤔
In that case we are interested in providing more JSON's

**Comment by robbat2** [comment]
@k0ste  yes, I would plan to use this for CI; do you have drives that differ significantly from these models I collected?

**Comment by NiceGuyIT** [comment]
Thank you @robbat2 !

The current implementation uses `smartctl --json --scan` for fake data. A switch needs to be added similar to PR #107 that adds support for which devices to scan. Any takers?

**Comment by k0ste** [comment]
> do you have drives that differ significantly from these models I collected?

I don’t know what to mean by significant, but yes, - I will prepare data on models that do not currently exist

**Pull request merged**
