### PR TITLE
* Bugfix  - Incorrect empty JSON. Added validation.

### PR DESCRIPTION
**Pull request by vagifzeynalov**
* https://github.com/Sheridan/smartctl_exporter/issues/19
* Update dependencies

### CODE REVIEW

**Comment by vagifzeynalov** [comment]
Yeah, I'll remove them.

**Comment by vagifzeynalov** [comment]
@lahwaacz removed and created a separate PR https://github.com/Sheridan/smartctl_exporter/pull/33

**Comment by SuperQ** [comment]
Would you please rebase this against current master?

**Comment by k0ste** [comment]
@vagifzeynalov can you rebase this PR?
Thanks!

**Comment by SuperQ** [comment]
@k0ste If you're interested in some of these PRs, maybe you can cherry-pick the commits and re-submit them.

**Comment by SuperQ** [comment]
Closing this as stale.

**Pull request closed without merging**
