### PR TITLE
Add container image badge

### PR DESCRIPTION
**Pull request by SuperQ**
Add a link to quay.io for the container image.

Signed-off-by: SuperQ <superq@gmail.com>

### CODE REVIEW

**Comment by SuperQ** [comment]
@kfox1111

**Comment by kfox1111** [comment]
When I go to that link, it asks me to login. Is it a private repo maybe?

**Comment by SuperQ** [comment]
OH! No wonder people were having problems. Somehow the container repo got marked private.

Fixed, please check again.

**Comment by kfox1111** [comment]
Ah. Now I see it. Thanks.

Pulling the image now, and just looking, I don't see smartctl in it. Do we need a 0.7.1 image with the previous docker fix?

**Pull request merged**
