### PR TITLE
Critical metrics for SCSI disks added, rebased

### PR DESCRIPTION
**Pull request by jthiltges**
This is a rebase of PR #21 against master, with all credit going to @wwwlde.

- Changes CounterValue to GaugeValue as requested
- Adds  `--log=error` in smartctl arguments to include SCSI error counters

### CODE REVIEW

**Comment by wwwlde** [comment]
Thanks @jthiltges! You are the best!

**Comment by k0ste** [comment]
@SuperQ

**Comment by k0ste** [comment]
@Nexucis maybe you can help with merges?

**Comment by Nexucis** [comment]
yeah that sounds ok.
I'm requesting a review from @SuperQ just in case he will have a last comment to do around that

**Comment by k0ste** [comment]
> yeah that sounds ok.
I'm requesting a review from @SuperQ just in case he will have a last comment to do around that

Thanks, we tag many times for SuperQ, we need someone less busy, for this project with merge rights
The community has made several PRs that make improvements - enough for the whole release!

**Comment by Nexucis** [comment]
we should probably give right to someone from the community that is more active and aware about this code. That should be the good way.

If there is a candidat that will be great !

**Comment by NiceGuyIT** [comment]
I'll look at this.

**Pull request merged**
