### PR TITLE
Release 0.7.0

### PR DESCRIPTION
**Pull request by SuperQ**
First prometheus-community release.

* [FEATURE] Add various new metrics #14
* [BUGFIX] Return the cached value if it's not time to scan again yet #18
* [BUGFIX] Fix exit code bit parsing #37

Signed-off-by: SuperQ <superq@gmail.com>

### CODE REVIEW

**Comment by kfox1111** [comment]
I may be doing something wrong, but I'm getting:
```
>> checking license header
license header checking failed:
./gjsonext.go
./logging.go
./main.go
./metrics.go
./options.go
./readjson.go
./smartctl.go
./smartctlinfo.go
```
While working on trunk.

**Comment by kfox1111** [comment]
[smartctl_exporter](https://github.com/prometheus-community/smartctl_exporter)/Dockerfile seems to be missing things. (no smartctl at least)

**Comment by kfox1111** [comment]
I was able to get it to build and work with the following Dockerfile:
```
FROM golang:1.18
RUN \
  git clone https://github.com/prometheus-community/smartctl_exporter && \
  cd smartctl* && \
  sed -i 's/common-all: precheck style check_license lint yamllint unused build 
test/common-all: precheck style lint yamllint unused build test/g' Makefile.comm
on && \
  sed -i 's/-race//' Makefile.common && \
  export CGO_ENABLED=0 && \
  make

FROM alpine
COPY --from=0 /go/smartctl_exporter/smartctl_exporter /bin/smartctl_exporter
RUN \
  apk add --no-cache --update smartmontools
COPY smartctl_exporter.yaml /etc/smartctl_exporter.yaml
CMD ["/bin/smartctl_exporter"]
```

One change needed to get it to pass the license check above, and one because I build it statically and one of the flags in Makefile.common isn't supported in that environment.

In testing its working fairly well. but it still suffers from this issue too: https://github.com/prometheus-community/smartctl_exporter/issues/13

**Comment by SuperQ** [comment]
The Dockerfile is fine, we pre-build binaries in Prometheus projects, rather than maintain multi-stage Docker builds.

**Comment by SuperQ** [comment]
Added a fix for the license check issue.

**Review by sysadmind — APPROVED** [review]
LGTM

**Comment by kfox1111** [comment]
The dockerfile looks to sill not include smartctl? Otherwise, everything else seems to be working well.

**Comment by SuperQ** [comment]
Oh, right, the actual smartctl tool.

**Pull request merged**
